[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
JuChrom = "202feb93-6b30-4454-a2e9-99db6534a6fb"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
XLSX = "fdbf4ff8-1666-58a4-91e7-1b58723a45e0"
